<?php

namespace App\PdfBrochure;

use App\Models\Car;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

// (BrochureBuilder + ImageEmbedder constructed per-call in newBuilder())

/**
 * Materialises a Car's CertiCheck brochure to durable storage.
 *
 * Used by:
 *   - the CarObserver / admin save flow: regenerates after edits
 *   - app/Console/Commands/RebuildBrochuresCommand: backfill + ops
 *   - admin "Regenerate" button (route TODO)
 *
 * NOT used by the public download endpoint. The public endpoint reads the
 * cached file only — it never invokes this service. That is what eliminates
 * the failure modes that produced `download.html` / `download.json`: there
 * is no synchronous work for an anonymous request to fail at.
 *
 * Status machine on `cars`:
 *   missing      → never generated, or invalidated
 *   generating   → in progress (set at start of generate())
 *   ready        → file written, byte-validated
 *   failed       → last generate() threw; error in brochure_error
 */
class BrochureGenerationService
{
    public function __construct(
        private readonly ChromiumRenderer $renderer,
    ) {}

    /**
     * Per-call builder: ImageEmbedder needs a fresh reportId + the current
     * filesystem config, so we can't hold a long-lived builder instance
     * in the container.
     */
    private function newBuilder(string $reportId): BrochureBuilder
    {
        $isS3       = config('filesystems.disks.public.driver') === 's3';
        $publicBase = $isS3 ? rtrim((string) config('filesystems.disks.public.url'), '/') : null;
        return new BrochureBuilder(new ImageEmbedder($reportId, $publicBase, $isS3));
    }

    /**
     * Generate (or regenerate) the cached brochure PDF for one car.
     *
     * Updates the car's brochure_* columns transactionally with the actual
     * file write. Throws on any failure (the caller decides whether to
     * surface it or just log + carry on).
     */
    public function generate(Car $car): void
    {
        $reportId = (string) Str::uuid();
        $started  = microtime(true);

        if (!$car->has_certicheck) {
            // Defensive: caller shouldn't ask for a brochure on a car
            // without CertiCheck, but if they do we record it and bail
            // rather than burn 10 seconds on a render that will be
            // hidden from the public anyway.
            $this->markStatus($car, 'missing', null, null, 'has_certicheck = false');
            return;
        }

        Log::channel('brochure')->info('pdf_brochure.regen.start', [
            'report_id' => $reportId,
            'car_id'    => $car->id,
        ]);

        $this->markStatus($car, 'generating', null, null, null);

        try {
            // 1) Pre-flight Chromium so we fail fast on a misconfigured deploy.
            $this->renderer->assertReady($reportId);

            // 2) Build the DTO + embed images.
            [$data, $embedder] = $this->newBuilder($reportId)->build($car, $reportId);

            // 3) Render HTML and hand to Chromium.
            $html = view('pdf-brochure.document', ['b' => $data])->render();
            $pdf  = $this->renderer->render($html, $reportId);

            if (!is_string($pdf) || substr($pdf, 0, 4) !== '%PDF') {
                throw new BrochureRenderException('Generated bytes do not start with %PDF.');
            }

            // 4) Write to a stable predictable path under the public disk.
            //    Use car id (immutable) not slug (mutable) so renames don't
            //    leak old files around.
            $path = sprintf('brochures/%d/certicheck.pdf', $car->id);
            Storage::disk('public')->put($path, $pdf);

            // 5) Update status atomically — the public route will start
            //    serving the new file the moment this row update lands.
            $this->markStatus($car, 'ready', $path, strlen($pdf), null);

            Log::channel('brochure')->info('pdf_brochure.regen.ok', [
                'report_id'   => $reportId,
                'car_id'      => $car->id,
                'path'        => $path,
                'bytes'       => strlen($pdf),
                'duration_ms' => (int) ((microtime(true) - $started) * 1000),
            ] + $embedder->stats());
        } catch (\Throwable $e) {
            $this->markStatus($car, 'failed', null, null, $this->shortMessage($e));

            Log::channel('brochure')->error('pdf_brochure.regen.failed', [
                'report_id'   => $reportId,
                'car_id'      => $car->id,
                'exception'   => get_class($e),
                'message'     => $e->getMessage(),
                'duration_ms' => (int) ((microtime(true) - $started) * 1000),
            ]);

            throw $e;
        }
    }

    /**
     * Drop the cached brochure file + status row. Called when a car loses
     * its CertiCheck flag, when admin forces a clean re-roll, or when the
     * car itself is being deleted (CarBrochureObserver::deleted).
     */
    public function invalidate(Car $car): void
    {
        if ($car->brochure_path) {
            try {
                Storage::disk('public')->delete($car->brochure_path);
            } catch (\Throwable $e) {
                Log::channel('brochure')->warning('pdf_brochure.regen.delete_failed', [
                    'car_id'  => $car->id,
                    'path'    => $car->brochure_path,
                    'message' => $e->getMessage(),
                ]);
            }
        }
        // If the car row is being deleted, do NOT write status — saveQuietly()
        // on a non-existent row re-inserts the car. The cars row going away
        // takes the status columns with it.
        if (!$car->exists) {
            return;
        }
        $this->markStatus($car, 'missing', null, null, null);
    }

    private function markStatus(Car $car, string $status, ?string $path, ?int $size, ?string $error): void
    {
        $car->forceFill([
            'brochure_status'       => $status,
            'brochure_path'         => $path,
            'brochure_size'         => $size,
            'brochure_error'        => $error,
            'brochure_generated_at' => $status === 'ready' ? now() : $car->brochure_generated_at,
        ])->saveQuietly();
        // saveQuietly so the CarObserver doesn't recursively re-mark us.
    }

    private function shortMessage(\Throwable $e): string
    {
        return substr(get_class($e) . ': ' . $e->getMessage(), 0, 990);
    }
}
